[package]
name = "egui_styled_widgets"
version = "0.1.0"
edition = "2024"

[dependencies]
egui.workspace = true

[dev-dependencies]
eframe = {workspace = true, default-features = true}

[lints]
workspace = true
